name: spotify-box
author: Aveek Saha
description: GitHub Action for injecting your top spotify tracks/artists into a gist

runs:
  using: 'node12'
  image: ./index.js

branding:
  icon: file-text
  color: green